cards_height:
  type: integer
  default: 350
  description: "Height in px for Desktop view. Mobile will wrap card content"
cards_min_width:
  type: float
  default: 0.75
  description: "Minimun height/width ratio for Desktop view. Mobile shows full width"
cards_max_width:
  type: float
  default: 0.75
  description: "Maximum height/width ratio for Desktop view. Mobile shows full width"
image_resize:
  type: enum
  default: "cover"
  choices:
    - contain
    - cover
    - fill
    - scale-down
    - none
  description: "How topic thumbnails should be resized to fit the cards."
corner_radius:
  type: integer
  default: 4
show_tag:
  type: bool
  default: true
show_image:
  type: bool
  default: true
show_category_link:
  type: bool
  default: true
show_title:
  type: bool
  default: true
show_excerpt:
  type: bool
  default: false
show_author:
  type: bool
  default: true
maximum_topic_count: 4
randomize_topics: true
featured_category:
  type: integer
  default: 0
featured_tags:
  type: list
  list_type: tag
  default: "featured"
topic_source:
  type: enum
  default: "latest"
  choices:
    - latest
    - top/all
    - top/yearly
    - top/quarterly
    - top/monthly
    - top/weekly
    - top/daily
show_component_heading:
  default: true
heading_text:
  default: "Featured Cards"
display_mobile: true
show_on:
  default: homepage
  type: enum
  choices:
    - homepage
    - top_menu
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>
plugin_outlet:
  type: enum
  default: "above-main-container"
  choices:
    - "above-main-container"
    - "below-site-header"
    - "discovery-list-container-top"
  description: "Advanced layout setting"
sort_by:
  type: enum
  default: "views"
  choices:
    - views
    - likes
  description: "choose a parameter to sort the cards"

